name: Build OpenWrt

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        target: [Lean]  # 确保 matrix.target 有值
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up OpenWrt feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Compile OpenWrt (generate cache directories)
        run: |
          cd openwrt
          make defconfig
          make download -j$(nproc)

      - name: Check cache paths
        run: |
          ls -R openwrt/dl || echo "dl/ does not exist"
          ls -R openwrt/staging_dir || echo "staging_dir/ does not exist"
          ls -R openwrt/build_dir || echo "build_dir/ does not exist"

      - name: Cache OpenWrt sources
        uses: actions/cache@v3
        with:
          path: |
            openwrt/dl
            openwrt/staging_dir
            openwrt/build_dir
          key: ${{ runner.os }}-openwrt-${{ matrix.target }}-${{ hashFiles('openwrt/feeds.conf.default') }}
          restore-keys: |
            ${{ runner.os }}-openwrt-${{ matrix.target }}-
            ${{ runner.os }}-openwrt-
            ${{ runner.os }}-

      - name: Build OpenWrt
        run: |
          cd openwrt
          make -j$(nproc)
